### ISSUE TITLE
Doesn't let me use vim

### ISSUE THREAD

**Issue by scotthaley** [campfighter/terminal-velocity#1]
Should be able to choose which editor is used

**Comment by scotthaley** [comment]
I wouldn't mind making this change, but do you have any ideas on ways to do configuration?

**Comment by campfighter** [comment]
We could introduce commander to parse command line arguments.

That raises another question, once a preference is set do we save it or make the caller pass it everytime?

**Comment by scotthaley** [comment]
Passing it every time would be really annoying, especially if there were multiple arguments.
What about a conf file that you just put in your home directory?
.termv or something

**Comment by campfighter** [comment]
Instead of the home directory could we just put it in the package folder? That way it would work even if you had multiple installs - local vs global.

**Comment by scotthaley** [comment]
I think that would be somewhat of an anti-pattern since finding that folder is kind of awkward and it could get overwritten with updates.

**Comment by campfighter** [comment]
it would just be the current folder, right? basically how im storing the notes folder. not the location where it was installed from, but the location it was installed to.

**Comment by scotthaley** [comment]
I think that would only make sense if you actually created the configuration through the app, but putting it in a folder in your home directory makes things a lot simpler since the app wouldn't have to care about writing the file.

**Comment by campfighter** [comment]
Right, I guess that's what I was thinking in my mind. That you could set it with command line arguments and it would update the config. 

I'm fine with either way though. Any configuration is better than what we have at the moment.

**Comment by campfighter** [comment]
If want take this on I can assign you to it. Otherwise I'll probably knock it out this weekend.

**Comment by campfighter** [comment]
Closed by #2
